Repository ios-course/swiftcowboys-team-project, pull requests merged in 2023-05, with the labels that each got.

#30 Issue#1 - Create the project with current environment and base architecture
  .gitignore
  .swift-version
  .swiftformat
  .swiftlint.yml
  CHANGELOG.md
  README.md
  Sleep Tracker/Sleep Tracker.xcodeproj/project.pbxproj
  Sleep Tracker/Sleep Tracker.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Sleep Tracker/Sleep Tracker.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Sleep Tracker/Sleep Tracker/Helpers/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  Sleep Tracker/Sleep Tracker/Helpers/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Sleep Tracker/Sleep Tracker/Helpers/Resources/Assets.xcassets/Contents.json
  Sleep Tracker/Sleep Tracker/Helpers/Resources/Preview Content/Preview Assets.xcassets/Contents.json
  Sleep Tracker/Sleep Tracker/Model/.gitkeep
  Sleep Tracker/Sleep Tracker/SleepTrackerApp.swift
  Sleep Tracker/Sleep Tracker/View/ContentView.swift
  Sleep Tracker/Sleep Tracker/ViewModel/.gitkeep
  Sleep Tracker/Sleep TrackerTests/Sleep_TrackerTests.swift
  Sleep Tracker/Sleep TrackerUITests/Sleep_TrackerUITests.swift
  Sleep Tracker/Sleep TrackerUITests/Sleep_TrackerUITestsLaunchTests.swift
Labels: EST: 2, high priority

#74 Update implementation of SleepSetupView
  Sleep Tracker/SleepTracker.xcodeproj/project.pbxproj
  Sleep Tracker/SleepTracker/Helpers/Image+AppImage.swift
  Sleep Tracker/SleepTracker/Helpers/Resources/Assets.xcassets/Sleeping_astronaut_horizontal.imageset/Contents.json
  Sleep Tracker/SleepTracker/Helpers/Resources/Assets.xcassets/Sleeping_astronaut_horizontal.imageset/Sleeping_astronaut_horizontal@2x.png
  Sleep Tracker/SleepTracker/Helpers/Resources/Assets.xcassets/Sleeping_astronaut_horizontal.imageset/Sleeping_astronaut_horizontal@3x.png
  Sleep Tracker/SleepTracker/Helpers/Resources/Assets.xcassets/Sleeping_astronaut_vertical.imageset/Contents.json
  Sleep Tracker/SleepTracker/Helpers/Resources/Assets.xcassets/Sleeping_astronaut_vertical.imageset/Sleeping_astronaut_vertical@2x.png
  Sleep Tracker/SleepTracker/Helpers/Resources/Assets.xcassets/Sleeping_astronaut_vertical.imageset/Sleeping_astronaut_vertical@3x.png
  Sleep Tracker/SleepTracker/View/DuringSleepView/DuringSleepView.swift
  Sleep Tracker/SleepTracker/View/ReusableViews/MultilineCenteredLabelView.swift
  Sleep Tracker/SleepTracker/View/SleepSetupView/SleepSetupView.swift
  Sleep Tracker/SleepTracker/View/SleepSetupView/Subviews/EstimatedSleepDurationLabelView.swift
Labels: enhancement

#76 Update implementation of DuringSleepView
  Sleep Tracker/SleepTracker/View/DuringSleepView/DuringSleepView.swift
Labels: enhancement

#82 Fix unit tests and remove unnecessary test target
  Sleep Tracker/SleepTracker.xcodeproj/project.pbxproj
  Sleep Tracker/SleepTracker.xcodeproj/xcshareddata/xcschemes/SleepTracker.xcscheme
  Sleep Tracker/SleepTracker.xcodeproj/xcshareddata/xcschemes/SleepTrackerTests.xcscheme
  Sleep Tracker/SleepTrackerTests/Helpers/Color+AppSchemeTests.swift
  Sleep Tracker/SleepTrackerTests/Helpers/Image+AppImageTests.swift
  Sleep Tracker/SleepTrackerTests/SleepTrackerTests.swift
  Sleep Tracker/SleepTrackerUITests/SleepTrackerUITests.swift
  Sleep Tracker/SleepTrackerUITests/SleepTrackerUITestsLaunchTests.swift
Labels: bug, enhancement

#87 Create extension for the `Date`
  Sleep Tracker/SleepTracker.xcodeproj/project.pbxproj
  Sleep Tracker/SleepTracker/Helpers/Date+ShortComponents.swift
  Sleep Tracker/SleepTracker/Helpers/UserDefaults+SharedAppPreferences.swift
  Sleep Tracker/SleepTrackerTests/Extensions/Date+CurrentTimeZone.swift
  Sleep Tracker/SleepTrackerTests/Extensions/UserDefaults+DeleteDataForAllTestKeys.swift
  Sleep Tracker/SleepTrackerTests/Extensions/UserDefaults+TestKey.swift
  Sleep Tracker/SleepTrackerTests/Helpers/Date+ShortComponentsTests.swift
  Sleep Tracker/SleepTrackerTests/Helpers/UserDefaults+SharedAppPreferencesTests.swift
Labels: enhancement
